import { StyleSheet } from "react-native";

 export const styles = StyleSheet.create({ // Styles for the leave check screen, defining the layout, colors, typography, and visual elements to create a cohesive and visually appealing user interface that aligns with the app's branding and design language.
  screen: { // The main container for the leave check screen, which takes up the full available space and sets the background color and padding for the content.
    flex: 1,
    backgroundColor: '#03110B',
    paddingHorizontal: 20,
    paddingTop: 8,
    justifyContent: 'space-between',
  },
  glowTop: { // A decorative element that creates a glowing effect at the top of the screen, using a semi-transparent color and a circular shape to add visual interest and reinforce the app's branding.
    position: 'absolute',
    top: -120,
    right: -40,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: 'rgba(33, 181, 110, 0.14)',
  },
  glowBottom: { // A decorative element that creates a glowing effect at the bottom of the screen, using a semi-transparent color and a circular shape to add visual interest and reinforce the app's branding.
    position: 'absolute',
    bottom: -120,
    left: -60,
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: 'rgba(16, 122, 78, 0.16)',
  },
  headerRow: { // The header row contains the close button and the header pill, which are spaced apart using flexbox properties to create a balanced layout at the top of the screen.
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  closeButton: { // The close button is a circular touchable element that allows users to quickly dismiss the leave check screen and return to the home screen, using a semi-transparent background and a border to make it visually distinct and easy to interact with.
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  headerPill: { // The header pill is a small, rounded container that displays the "Leave-home alert" label, using a semi-transparent background and a border to make it visually distinct and reinforce the app's branding.
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(9, 28, 20, 0.88)',
    borderWidth: 1,
    borderColor: 'rgba(147, 255, 196, 0.16)',
  },
  headerPillDot: { // A small dot that appears to the left of the header pill text, using a bright green color to indicate that the leave-home alert is active and to draw attention to the header pill.
    width: 8,
    height: 8,
    borderRadius: 999,
    marginRight: 8,
    backgroundColor: '#62F2A2',
  },
  headerPillText: { // The text style for the header pill, which uses a bright green color and uppercase letters to make it visually distinct and reinforce the app's branding.
    color: '#D5FBE6',
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  card: { // The main card container that holds the content of the leave check screen, using a dark background color, rounded corners, and a subtle border to create a visually appealing and cohesive design that aligns with the app's branding.
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(8, 21, 16, 0.86)',
    borderRadius: 32,
    borderWidth: 1,
    borderColor: 'rgba(132, 255, 188, 0.16)',
    paddingHorizontal: 22,
    paddingVertical: 28,
    shadowColor: '#00FF88',
    shadowOpacity: 0.12,
    shadowRadius: 28,
    shadowOffset: { width: 0, height: 12 },
  },
  iconWrap: { // A circular container that holds the shield checkmark icon, using a semi-transparent background and a border to make it visually distinct and reinforce the app's branding, while also creating a sense of security and trust for the user.
    width: 72,
    height: 72,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(108, 255, 174, 0.12)',
    marginBottom: 18,
    borderWidth: 1,
    borderColor: 'rgba(155, 255, 195, 0.24)',
  },
  iconCore: { // A smaller circular container that sits inside the icon wrap, using a bright green color to create a strong visual contrast and draw attention to the shield checkmark icon, while also reinforcing the app's branding and creating a sense of security and trust for the user.q
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#7EFFBC',
  },
  brandLabel: {
    color: '#89D7A7',
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  title: { // The title style for the leave check screen, which uses a bright green color, large font size, and bold weight to make it visually distinct and reinforce the app's branding, while also conveying a sense of urgency and importance to the user.
    color: '#F4FFF8',
    fontSize: 31,
    lineHeight: 37,
    fontWeight: '800',
    marginBottom: 10,
  },
  body: { // The body text style for the leave check screen, which uses a softer green color, medium font size, and regular weight to create a visually appealing and easy-to-read design that provides clear information to the user about the leave-home alert and encourages them to take action. 
    color: '#BDD9C8',
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 16,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)',
    marginBottom: 10,
  },
  metaText: {
    flex: 1,
    color: '#9EB5A7',
    fontSize: 13,
    lineHeight: 18,
    marginLeft: 8,
  },
  actionHint: {
    color: '#7EFFBC',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 14,
  },
  chipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 20,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    marginRight: 10,
    marginBottom: 10,
    backgroundColor: 'rgba(20, 49, 37, 0.94)',
    borderWidth: 1,
    borderColor: 'rgba(132, 255, 188, 0.12)',
  },
  chipText: {
    color: '#E8FFF1',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
    marginBottom: 18,
  },
  sectionTitle: {
    color: '#F4FFF8',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 6,
  },
  sectionCopy: {
    color: '#9EB5A7',
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 22,
  },
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#7EFFBC',
    borderRadius: 20,
    paddingVertical: 16,
    marginBottom: 12,
  },
  primaryButtonText: {
    color: '#03170F',
    fontSize: 16,
    fontWeight: '800',
    marginRight: 8,
  },
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    paddingVertical: 15,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  secondaryButtonText: {
    color: '#D8FBE7',
    fontSize: 15,
    fontWeight: '700',
    marginLeft: 8,
  },

  /* NEW VERIFIED STATE STYLES - Added to bridge the Leave Check with the History page model */
  verifiedCard: { // Layout that transforms the chip into a card matching the history log entries.
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(20, 49, 37, 0.94)',
    borderRadius: 20,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#4ADE80',
    width: '100%',
  },
  circleProfile: { // The circular container for item photos/icons to create the "Profile" look.
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#9BFFC3',
    marginRight: 14,
    overflow: 'hidden',
  },
  iconWrapSmall: { // Muted spacing for the chip icon before verification.
    marginRight: 4,
  },
  verifiedTextContent: { // Aligns the item name and verification status vertically.
    flex: 1,
    justifyContent: 'center',
  },
  verifiedItemName: { // Font style for verified items.
    color: '#F4FFF8',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 2,
  },
  verifiedBadge: { // Container for the green verification badge.
    flexDirection: 'row',
    alignItems: 'center',
  },
  verifiedBadgeText: { // Small green uppercase text for the verified status.
    color: '#4ADE80',
    fontSize: 11,
    fontWeight: '600',
    marginLeft: 4,
    textTransform: 'uppercase',
  },
});